# Generated by Django 5.2.7 on 2026-01-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the Title of the blog', max_length=255)),
                ('sub_title', models.CharField(blank=True, help_text='Enter the Sub-title of the blog', max_length=255, null=True)),
                ('author', models.CharField(blank=True, help_text='Author of the blog', max_length=255, null=True)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags', null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image', null=True, upload_to='blog_covers/')),
                ('description', models.TextField(blank=True, help_text='Enter the blog Description', null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the blog active?')),
                ('send_as_newsletter', models.BooleanField(default=False, help_text='Send this blog as a newsletter?')),
                ('category', models.ForeignKey(blank=True, help_text='Category of the blog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.blogcategory')),
            ],
        ),
    ]
