# Generated by Django 5.2.7 on 2026-01-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('subject', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
