# Generated by Django 5.2.7 on 2026-01-22 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contactus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_header', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(blank=True, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
