# Generated by Django 5.2.7 on 2026-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_newsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowKnowIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_nepali_english', models.CharField(max_length=255)),
                ('natural_english', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
