# Generated by Django 5.2.7 on 2026-01-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpandVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=255)),
            ],
        ),
    ]
