# Generated by Django 5.2.7 on 2026-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_expandvocab'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowknowit',
            name='forced_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nowknowit',
            name='used_status',
            field=models.BooleanField(default=False),
        ),
    ]
