# Generated by Django 5.2.7 on 2026-01-28 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_nowknowit_forced_publish_nowknowit_used_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandvocab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expandvocab',
            name='forced_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expandvocab',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expandvocab',
            name='used_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nowknowit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nowknowit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expandvocab',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
