# Generated by Django 5.2.7 on 2026-03-04 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_expandvocab_created_at_expandvocab_forced_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletters',
            name='save_as_template',
            field=models.BooleanField(default=False),
        ),
    ]
