# Generated by Django 5.2.7 on 2026-03-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_newsletters_created_at_newsletters_save_as_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandvocab',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
