# Generated by Django 5.2.7 on 2026-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_subscriptionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
