# Generated by Django 5.2.7 on 2026-02-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_subscriptionhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('inactive', 'Inactive')], default='pending', max_length=255),
        ),
    ]
