# Generated by Django 5.2.7 on 2026-02-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_subscriptionhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlog',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('inactive', 'Inactive'), ('deactivated', 'Deactivated')], default='pending', max_length=255),
        ),
    ]
