# Generated by Django 5.2.7 on 2026-02-27 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_subscriptionlog_on_trial_and_more'),
        ('user', '0005_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='new_amount',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='new_payment_mode',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='old_amount',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='old_payment_mode',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='old_status',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='school',
        ),
        migrations.AddField(
            model_name='subscriptionlog',
            name='changed_fields',
            field=models.JSONField(default=dict, help_text='Stores only changed fields with old and new values'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=255)),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('bank', 'Bank Transfer')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('inactive', 'Inactive'), ('deactivated', 'Deactivated')], default='pending', max_length=50)),
                ('on_trial', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='user.school')),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionlog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='school.subscription'),
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
    ]
