# Generated by Django 5.2.7 on 2026-02-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_subscriptionlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deactivate', 'Deactivate')], default='inactive', max_length=50),
        ),
    ]
