# Generated by Django 5.2.7 on 2026-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking_instruction', models.TextField()),
                ('listening_instruction', models.TextField()),
                ('writing_instruction', models.TextField()),
                ('reading_instruction', models.TextField()),
            ],
        ),
    ]
