# Generated by Django 5.2.7 on 2026-01-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_settings', '0003_termsandconditions'),
        ('user', '0002_userprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('grade', models.CharField(max_length=50)),
                ('mark_all_grade', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.school')),
            ],
        ),
    ]
