# Generated by Django 5.2.7 on 2026-01-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_settings', '0004_exampause'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampause',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
