# Generated by Django 5.2.7 on 2026-01-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_settings', '0005_exampause_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampause',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
