# Generated by Django 5.2.7 on 2026-01-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_settings', '0006_alter_exampause_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='effective_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
