# Generated by Django 5.2.7 on 2026-01-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('instructions', models.TextField()),
                ('use_default_instruction', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingAcitivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_1', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('answer_3', models.CharField(max_length=255)),
                ('answer_4', models.CharField(max_length=255)),
                ('is_correct_answer', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('true_false', 'True_False'), ('mcq', 'MCQ'), ('note_completion', 'NoteCompletion'), ('sentence_Completion', 'SentenceCompletion'), ('summary_completion', 'SummaryCompletion')], max_length=255)),
                ('reading_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.readingactivity')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('part1', 'Part 1'), ('extended_question', 'Extended Question')], max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='question_attachment/')),
                ('durations', models.DecimalField(decimal_places=2, max_digits=5)),
                ('text_question', models.CharField(blank=True, max_length=255, null=True)),
                ('speaking_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.speakingactivity')),
            ],
        ),
        migrations.CreateModel(
            name='speakingActivitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('part1', 'Part 1'), ('extended_question', 'Extended Question')], max_length=255)),
                ('sample_question', models.FileField(blank=True, null=True, upload_to='samplequestion/')),
                ('sample_answer', models.FileField(blank=True, null=True, upload_to='sampleanswer/')),
                ('sample_text_question', models.CharField(blank=True, max_length=255, null=True)),
                ('speaking_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.speakingactivity')),
            ],
        ),
        migrations.AddField(
            model_name='speakingactivity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='readingactivity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
