# Generated by Django 5.2.7 on 2026-01-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at_task_status_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningactivity',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
