# Generated by Django 5.2.7 on 2026-01-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_speakingactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='speakingActivitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('part1', 'Part 1'), ('extended_question', 'Extended Question')], max_length=255)),
                ('sample_question', models.FileField(blank=True, null=True, upload_to='samplequestion/')),
                ('sample_answer', models.FileField(blank=True, null=True, upload_to='sampleanswer/')),
                ('sample_text_question', models.CharField(blank=True, max_length=255, null=True)),
                ('speaking_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.speakingactivity')),
            ],
        ),
    ]
