# Generated by Django 5.2.7 on 2026-01-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_listeningactivity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingactivity',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speakingactivity',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speakingactivityquestion',
            name='durations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='writingactivity',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
