# Generated by Django 5.2.7 on 2026-01-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_speakingactivitysample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingactivity',
            name='duration',
        ),
    ]
