# Generated by Django 5.2.7 on 2026-02-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_readingactivity_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingactivityquestion',
            name='instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
