# Generated by Django 5.2.7 on 2026-01-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_speakingactivity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingactivity',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
