# Generated by Django 5.2.7 on 2026-02-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_speakingactivityquestion_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('did_completed_speaking_activity', models.BooleanField(default=False)),
                ('did_completed_reading_activity', models.BooleanField(default=False)),
                ('did_completed_listening_activity', models.BooleanField(default=False)),
                ('did_completed_writing_activity', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
