# Generated by Django 5.2.7 on 2026-01-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_speakingactivity_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('part1', 'Part 1'), ('extended_question', 'Extended Question')], max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='question_attachment/')),
                ('durations', models.DecimalField(decimal_places=2, max_digits=5)),
                ('text_question', models.CharField(blank=True, max_length=255, null=True)),
                ('speaking_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.speakingactivity')),
            ],
        ),
    ]
