# Generated by Django 5.2.7 on 2026-02-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_usertaskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingactivity',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
