# Generated by Django 5.2.7 on 2026-01-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_readingactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingAcitivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_1', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('answer_3', models.CharField(max_length=255)),
                ('answer_4', models.CharField(max_length=255)),
                ('is_correct_answer', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('true_false', 'True_False'), ('mcq', 'MCQ'), ('note_completion', 'NoteCompletion'), ('sentence_Completion', 'SentenceCompletion'), ('summary_completion', 'SummaryCompletion')], max_length=255)),
                ('reading_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.readingactivity')),
            ],
        ),
    ]
