# Generated by Django 5.2.7 on 2026-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_readingactivity_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingactivity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reading_passage/'),
        ),
    ]
