# Generated by Django 5.2.7 on 2026-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_readingactivity_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingacitivityquestion',
            name='answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='readingacitivityquestion',
            name='answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='readingacitivityquestion',
            name='answer_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='readingacitivityquestion',
            name='answer_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='readingacitivityquestion',
            name='type',
            field=models.CharField(choices=[('true_false', 'True_False'), ('mcq', 'MCQ'), ('note_completion', 'NoteCompletion'), ('sentence_completion', 'SentenceCompletion'), ('summary_completion', 'SummaryCompletion')], max_length=255),
        ),
    ]
