# Generated by Django 5.2.7 on 2026-02-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_readingacitivityquestion_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingacitivityquestion',
            name='instruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speakingactivity',
            name='instruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speakingactivityquestion',
            name='instruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
