# Generated by Django 5.2.7 on 2026-01-18 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_listeningactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('part1', 'part1'), ('form_question', 'form_question')], max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('answer_1', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('answer_3', models.CharField(max_length=255)),
                ('answer_4', models.CharField(max_length=255)),
                ('is_correct_answer', models.CharField(max_length=255)),
                ('listening_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.listeningactivity')),
            ],
        ),
    ]
