# Generated by Django 5.2.7 on 2026-01-18 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_listeningactivityquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instruction', models.TextField()),
                ('writing_sample', models.CharField(max_length=255)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
