# Generated by Django 5.2.7 on 2026-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_readingacitivityquestion_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingactivity',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
