# Generated by Django 5.2.7 on 2026-02-08 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_writingactivity_issue_alter_writingactivity_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningactivityquestion',
            name='bundle_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='readingacitivityquestion',
            name='bundle_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
