# Generated by Django 5.2.7 on 2026-02-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_writingactivity_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingactivity',
            name='writing_sample',
            field=models.TextField(blank=True, null=True),
        ),
    ]
