# Generated by Django 5.2.7 on 2026-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_writingactivity_writing_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingactivity',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
