# Generated by Django 5.2.7 on 2026-02-08 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_listeningactivityquestion_bundle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningactivityquestion',
            name='listening_activity',
        ),
        migrations.RemoveField(
            model_name='listeningactivityquestion',
            name='type',
        ),
        migrations.AddField(
            model_name='listeningactivityquestion',
            name='question_type',
            field=models.CharField(blank=True, choices=[('matching_info', 'Matching_info'), ('mcq', 'Mcq'), ('note_completion', 'Note_completion')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ListeningActivityPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('Part1-Conversation ', 'Part1-Conversation'), ('Part2-Talk ', 'Part2-Talk'), ('Part3-Lecture ', 'Part3-Lecture ')], max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='listening_part_file/')),
                ('instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listening_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.listeningactivity')),
            ],
        ),
        migrations.AddField(
            model_name='listeningactivityquestion',
            name='listening_activity_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.listeningactivitypart'),
        ),
    ]
