# Generated by Django 5.2.7 on 2026-02-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_listeningactivityquestion_listening_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningactivitypart',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
