# Generated by Django 5.2.7 on 2026-02-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_listeningactivitypart_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningactivitypart',
            name='part',
            field=models.CharField(choices=[('Part1-Conversation', 'Part1-Conversation'), ('Part2-Talk', 'Part2-Talk'), ('Part3-Lecture', 'Part3-Lecture')], max_length=255),
        ),
    ]
