# Generated by Django 5.2.7 on 2026-02-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_listeningactivitypart_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningactivityquestion',
            name='answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listeningactivityquestion',
            name='answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listeningactivityquestion',
            name='answer_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listeningactivityquestion',
            name='answer_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
