# Generated by Django 5.2.7 on 2026-01-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattempts',
            name='activity_type',
            field=models.CharField(choices=[('speaking_activity', 'Speaking Activity'), ('listening_activity', 'Listening Activity'), ('writing_activity', 'Writing Activity'), ('reading_activity', 'Reading Activity')], max_length=255),
        ),
    ]
