# Generated by Django 5.2.7 on 2026-01-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
