# Generated by Django 5.2.7 on 2026-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
