# Generated by Django 5.2.7 on 2026-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_user_type_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('parent', 'Parent'), ('student', 'Student'), ('school', 'School')], max_length=20, null=True),
        ),
    ]
