# Generated by Django 5.2.7 on 2026-01-13 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='schoollogo/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.district'),
        ),
    ]
