# Generated by Django 5.2.7 on 2026-01-13 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_school_logo_alter_school_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(limit_choices_to={'userprofile__user_type': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_school_relations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.school')),
                ('student', models.ForeignKey(limit_choices_to={'userprofile__user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_school_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'school', 'parent')},
            },
        ),
    ]
